- hosts: all
  become: yes
  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: latest
    
    - name: start service
      service:
        name: apache2
        state: restarted