- hosts: all
  become: yes
  become_method: sudo
  remote_user: yash
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day

  - name: install JDK 11
    apt:
      name: openjdk-11-jdk
      state: present

  - name: add tomcat group
    group:
      name: tomcat

  - name: add tomcat user
    user:
      name: tomcat
      group: tomcat
      home: /user/share/tomcat
      createhome: no

  - name: create /opt/tomcat directory
    file:
      path: /opt/tomcat
      state: directory
      mode: 0755

  - name: download & unarchive
    unarchive:
      src: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.37/bin/apache-tomcat-9.0.37.tar.gz
      dest: /opt/tomcat
      remote_src: yes
      extra_opts: [--strip-components=1]

  - name: Change ownership
    file:
      path: /opt/tomcat
      owner: tomcat
      group: tomcat
      mode: "u+rwx,g+rx,o=rx"
      recurse: yes
      state: directory

  - name: make tomcat.service
    file:
      path: /etc/systemd/system/tomcat.service
      state: touch

  - name: edit tomcat.service
    blockinfile:
      dest: /etc/systemd/system/tomcat.service
      insertafter:
      block: |
        [Unit]
        Description = Apache Tomcat 9
        After = syslog.target network.target
        [Service]
        User = tomcat
        Group = tomcat
        Type = oneshot
        PIDFile =/usr/local/apache-tomcat-9.0.37/tomcat.pid
        RemainAfterExit = yes
        ExecStart =/usr/local/apache-tomcat-9.0.37/bin/startup.sh
        ExecStop =/usr/local/apache-tomcat-9.0.37/bin/shutdown.sh
        ExecReStart =/usr/local/apache-tomcat-9.0.37/bin/shutdown.sh;/usr/local/apache-tomcat-9.0.37/bin/startup.sh
        [Install]
        WantedBy = multi-user.target

  - name: chmod 755 tomcat.service
    file:
      path: /etc/systemd/system/tomcat.service
      mode: 0755

  - name: to start tomcat services
    shell: "{{tomcat}}/apache-tomcat-8.5.38/bin/startup.sh"