---
# tasks file for tomcatrole.yml---
# tasks file for tomcatrole
- name: install apache
  apt:
    name: apache2
    state: present

- name: restart apache
  service:
    name: apache2
    state: restarted